CREATE DATABASE VIDEOTECA
USE VIDEOTECA

CREATE TABLE INFORMACION(
  NOMBRECOMPLETO VARCHAR(200),
  DIRECCION VARCHAR(150),
  PELICULASRENTADAS VARCHAR(MAX),
  SALUDO VARCHAR(4))

INSERT INTO INFORMACION
VALUES 
('CARMEN RUIZ','JR CUZCO 234','PIRATES DEL CARIBE ,TITANIC , BOB ESPONJA','SRA'),
('MARIA CAMARGO','AV SUCURSALES 1234','SPIDERMAN ,LO QUE EL VIENTO SE LLEVO , HOST','SRA'),
('MANUEL TAPIA','CALLE LOS ALISOS 109','LA MOMIA ,LOS GALACTICOS , EL ARO','SR'),
('RAFER ORTIZ','CALLE EL SALVADOR 129','LA MOMIA ,TITANIC , SPIDERMAN','SR')
SELECT * FROM INFORMACION

/*
Tipos de Formas Normales en DBMS
- 1FN(Primera Forma Normal) .-
  -Garantiza que la tabla de la BD este organizada de manera que 
  cada columna contenga valores atomicos(Divisible)
  -Cada Registro Sea Unico.
  -Eliminar grupos repetidos.
*/

CREATE TABLE INFORMACION_1FN(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRECOMPLETO VARCHAR(200),
	DIRECCION VARCHAR(150),
	PELICULASRENTADAS VARCHAR(MAX),
	SALUDO VARCHAR(4))

INSERT INTO INFORMACION_1FN
VALUES 
('CARMEN RUIZ','JR CUZCO 234','PIRATES DEL CARIBE','SRA'),
('CARMEN RUIZ','JR CUZCO 234','TITANIC','SRA'),
('CARMEN RUIZ','JR CUZCO 234','BOB ESPONJA','SRA'),

('MARIA CAMARGO','AV SUCURSALES 1234','SPIDERMAN','SRA'),
('MARIA CAMARGO','AV SUCURSALES 1234','LO QUE EL VIENTO SE LLEVO','SRA'),
('MARIA CAMARGO','AV SUCURSALES 1234','HOST','SRA'),

('MANUEL TAPIA','CALLE LOS ALISOS 109','LA MOMIA','SR'),
('MANUEL TAPIA','CALLE LOS ALISOS 109','LOS GALACTICOS','SR'),
('MANUEL TAPIA','CALLE LOS ALISOS 109','EL ARO','SR'),

('RAFEL ORTIZ','CALLE EL SALVADOR 129','LA MOMIA','SR'),
('RAFEL ORTIZ','CALLE EL SALVADOR 129','TITANIC','SR'),
('RAFEL ORTIZ','CALLE EL SALVADOR 129','SPIDERMAN','SR')

SELECT * FROM INFORMACION_1FN

/*

- 2FN(Segunda Forma Normal) .-
  -Este EN 1FN
  -Cada Registro Sea Unico.
  -Clave principal de una solo columna que no dependa funcionalmente de ningun subconjunto de relacion de la 
   clave candidata
*/

CREATE TABLE MIEMBROS_2FN(
    IDMIEMBRO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRECOMPLETO VARCHAR(200),
	DIRECCION VARCHAR(150),
	SALUDO VARCHAR(4))

INSERT INTO MIEMBROS_2FN
VALUES 
('CARMEN RUIZ','JR CUZCO 234','SRA'),
('MARIA CAMARGO','AV SUCURSALES 1234','SRA'),
('MANUEL TAPIA','CALLE LOS ALISOS 109','SR'),
('RAFEL ORTIZ','CALLE EL SALVADOR 129','SR')

SELECT * FROM MIEMBROS_2FN


CREATE TABLE PELICULAS_2FN(
  IDPELICULA INT IDENTITY(1,1) PRIMARY KEY,
  PELICULAS VARCHAR(100),
  MIEMBRO_ID INT,
  FOREIGN KEY(MIEMBRO_ID) REFERENCES MIEMBROS_2FN(IDMIEMBRO))

INSERT INTO PELICULAS_2FN
VALUES
('PIRATES DEL CARIBE',17),
('TITANIC',17),
('BOB ESPONJA',17),
('SPIDERMAN',18),
('LO QUE EL VIENTO SE LLEVO',18),
('HOST',18),
('LA MOMIA',19),
('LOS GALACTICOS',19),
('EL ARO',19),
('LA MOMIA',20),
('TITANIC',20),
('SPIDERMAN',20)
SELECT * FROM MIEMBROS_2FN
SELECT * FROM PELICULAS_2FN


/*

- 3FN(Tercera Forma Normal) .-
  -Estar EN 2FN
  -No Tener dependencias funcionales transitivas
  
*/

DROP TABLE MIEMBROS_3FN
CREATE TABLE MIEMBROS_3FN(
    IDMIEMBRO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRECOMPLETO VARCHAR(200),
	DIRECCION VARCHAR(150),
	IDSALUDO INT,
	FOREIGN KEY (IDSALUDO) REFERENCES SALUDOS_3FN(IDSALUDO)
	)

INSERT INTO MIEMBROS_3FN
VALUES 
('CARMEN RUIZ','JR CUZCO 234',1),
('MARIA CAMARGO','AV SUCURSALES 1234',1),
('MANUEL TAPIA','CALLE LOS ALISOS 109',2),
('RAFEL ORTIZ','CALLE EL SALVADOR 129',2)	

CREATE TABLE SALUDOS_3FN(
IDSALUDO INT IDENTITY(1,1) PRIMARY KEY,
SALUDO VARCHAR(10))

INSERT INTO SALUDOS_3FN
VALUES('SRA'),('SR')

SELECT * FROM SALUDOS_3FN

CREATE TABLE PELICULAS_3FN(
  IDPELICULA INT IDENTITY(1,1) PRIMARY KEY,
  PELICULAS VARCHAR(100),
  MIEMBRO_ID INT,
  FOREIGN KEY(MIEMBRO_ID) REFERENCES MIEMBROS_3FN(IDMIEMBRO))

INSERT INTO PELICULAS_2FN
VALUES
('PIRATES DEL CARIBE',17),
('TITANIC',17),
('BOB ESPONJA',17),
('SPIDERMAN',18),
('LO QUE EL VIENTO SE LLEVO',18),
('HOST',18),
('LA MOMIA',19),
('LOS GALACTICOS',19),
('EL ARO',19),
('LA MOMIA',20),
('TITANIC',20),
('SPIDERMAN',20)
