create database dbempesasac
use dbempesasac

CREATE TABLE CLIENTES (
  CLIENTEID INT PRIMARY KEY,
  NOMBRE VARCHAR(100),
  DIRECCION NVARCHAR(200));

CREATE TABLE PEDIDOS (
  PEDIDOID INT PRIMARY KEY,
  CLIENTEID INT,
  PRODUCTO NVARCHAR(100),
  CANTIDAD INT,
  FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID));

INSERT INTO CLIENTES (CLIENTEID,NOMBRE,DIRECCION)
VALUES(1,'Juan Perez','Calle Capon 123')

INSERT INTO PEDIDOS (PEDIDOID,CLIENTEID,PRODUCTO,CANTIDAD)
VALUES(1,1,'LAPTOP',2),
      (2,1,'MOUSE',4); 

--MINIMIZACION DE REDUNDANCIA
--NORMALIZAR CORRECTAMENTE DICHA TABLA EN DOS
CREATE TABLE Pedidos (
    PedidoID INT PRIMARY KEY,
    ClienteNombre NVARCHAR(100),
    ClienteDireccion NVARCHAR(200),
    Producto NVARCHAR(100),
    Cantidad INT
);

--MAXIMIZACION DE LA COHERENCIA
-- Datos no contradictorios
INSERT INTO PEDIDOS(PEDIDOID,CLIENTEID,PRODUCTO,CANTIDAD)
VALUES(3,999,'LAPTOP',2)--ClienteID 999 no existe en la tabla clientes

INSERT INTO PEDIDOS(PEDIDOID,CLIENTEID,PRODUCTO,CANTIDAD)
VALUES(3,1,'TECLADO',0)--La cantidad debe ser mayor a 0

ALTER TABLE Pedidos
ADD CONSTRAINT CK_Cantidad_Positiva
CHECK (CANTIDAD>0)

select * from pedidos
delete from PEDIDOS where PEDIDOID=3

--Optimización del Acceso a Datos
SELECT *
FROM PEDIDOS
WHERE CLIENTEID=1;

CREATE INDEX IDX_CLIENTEID ON Pedidos(Clienteid)
